[project]
name = "backend"
version = "0.2.0"
description = "FastAPI backend for NVIDIA Parakeet Vietnamese transcription"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.0",
    "nemo_toolkit[asr]>=2.6,<2.7",
    "python-dotenv>=1.1.1",
    "python-multipart>=0.0.20",
    "torch==2.7.1",
    "uvicorn>=0.35.0",
]

[tool.uv.sources]
torch = [{ index = "pytorch-cu128", marker = "platform_system == 'Linux'" }]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
